### PR TITLE
Added entity type changes to EntityListener.

### PR DESCRIPTION
**Pull request by wlmiller**
Is this what you had in mind for #101?  It seems to work, but if there's a better way to call the methods in `DefaultEntity.java`, I'd love to hear it.

### CODE REVIEW

**Comment by Ellzord** [comment]
I think this has identified an actual issue with the context of `EntityListener`!

We should refactor:
- `EntityListener` to `EntityContainerListener`
- `EntityEvent` to `EntityContainerEvent`

Because really these events only fire for child events and that isn't clear by the name.

We should then create `EntityListener` and `EntityEvent` again but for the context of an `Entity`. It should contain the methods from #101 but also `entityKilled(EntityEvent event)` and maybe some transportation ones like exported, imported or transferred or received?

In the future (if you agree I'll make an issue) we can also create `AttributeContainerListener` and `AttributeContainerEvent` for trigger events for the entire container (not named type events).

The above means we have proper contextual event triggering and we could do stuff like

``` java
entity.addEntityListener(new EntityListener() {

    public void entityKilled(EntityEvent event) {
        // Update score
    }
}
```

Rather than putting it on the level above and filter out specific entities (if we only wanted to do this for a player or something).

What are your thoughts?

**Comment by Ellzord** [comment]
This is quite a large change so I can attempt to do this over this week (doing #52 currently).

**Comment by wlmiller** [comment]
I think that makes a lot of sense,  The implementation you describe is definitely more intuitive than the way it works now.  I'll go ahead and close this PR - I'd be glad to help with the refactor, but I'll actually be out of town for a few days.

**Comment by Ellzord** [comment]
Glad you agree. That actually gives me some time to finish up the entity annotations (you can review when you're back). I'm more than happy for you to help with the refactor - we can spilt it all up if it's non-trivial!

Drop me a line via email (ElliotFord@live.co.uk) or [Gitter chat](https://gitter.im/Ellzord/JALSE)

**Pull request closed without merging**
